[package]
name = "cpc"
version = "0.1.0"
edition = "2021"

[dependencies]
insta = { version = "1.42.0", features = ["ron"] }
nom = "^7.1.3"
serde = { version = "1.0.217", features = ["derive"] }

[lib]
test = false
doctest = false

[[bin]]
name = "cpc"
test = false
